# Configuration for KKI Auto-Deploy System
defaults:
  verification:
    timeout: 30000
    httpTimeout: 10000
    cleanupVerificationFile: true
    retries: 3
    retryDelay: 2000
  excludes:
    - "*.tmp"
    - "*.log"
    - ".git/**"
    - ".gitignore"
    - "README.md"
    - "node_modules/**"
    - ".env*"
    - "deployment-*"
    - "AUTO-DEPLOY-MK/**"
    - "_backup*/**"
    - "_documentation/**"
    - "_deployment-system/**"

# Deployment targets
# Path Logic:
# - remoteRoot: Base FTP directory (e.g., "/httpdocs")
# - project.parts.remotePath: Subdirectory within remoteRoot for FTP (e.g., "/ki")
# - project.parts.webPath: Web URL path for verification (e.g., "/ki")
# - FTP Final path: remoteRoot + remotePath = "/httpdocs/ki"
# - Web Final URL: https://domain + webPath = "https://kombaecher.de/ki"
#
# Environment Variables Required:
# - FTP_USER: FTP username from .env
# - FTP_PASSWORD: FTP password from .env
targets:
  production:
    method: ftp
    remoteRoot: "/httpdocs"
    domain: "kombaecher.de"
    ftp:
      host: "ftp.kombaecher.de"
      user: "${FTP_USER}"
      password: "${FTP_PASSWORD}"
      timeout: 30000

  local:
    method: copy
    localPath: "./_local-test"
    domain: "localhost:3021"

# Projects configuration
projects:
  web:
    localSource: "./apps/web"
    localBuild: "./apps/web/out"
    buildCommand: "cd apps/web && npm run build && npm run export"

    # Project parts - different sections of the project
    parts:
      default:
        include:
          - "**/*"
        remotePath: "/ki" # FTP path: /httpdocs/ki
        webPath: "/ki" # Web URL: https://kombaecher.de/ki

      root-app:
        include:
          - "app.js"
          - "package.json"  
        remotePath: "/" # FTP path: /httpdocs (root level)
        webPath: "/" # Web URL root level

    # Verification settings
    verify:
      enabled: true
      fileTemplate: "deploy-verify-{timestamp}.html"
      urlTemplate: "https://{domain}{webPath}/{file}"

  api:
    localSource: "./apps/api"
    localBuild: "./apps/api"
    buildCommand: "" # Python doesn't need building

    parts:
      default:
        include:
          - "**/*.py"
          - "**/*.txt"
          - "**/.htaccess"
        remotePath: "/ki/api" # FTP path: /ki/api
        webPath: "/ki/api" # Web URL: https://kombaecher.de/ki/api

    verify:
      enabled: true
      fileTemplate: "health-check.html"
      urlTemplate: "https://{domain}{webPath}/health"

  # Example configurations for other frameworks
  react-app:
    localSource: "./src"
    localBuild: "./build"
    buildCommand: "npm run build"
    parts:
      default:
        include: ["**/*"]
        remotePath: "/"
    verify:
      enabled: true
      fileTemplate: "deploy-verify-{timestamp}.html"
      urlTemplate: "https://{domain}/{file}"

  vue-app:
    localSource: "./src"
    localBuild: "./dist"
    buildCommand: "npm run build"
    parts:
      default:
        include: ["**/*"]
        remotePath: "/"
    verify:
      enabled: true
      fileTemplate: "deploy-verify-{timestamp}.html"
      urlTemplate: "https://{domain}/{file}"

  angular-app:
    localSource: "./src"
    localBuild: "./dist"
    buildCommand: "ng build --prod"
    parts:
      default:
        include: ["**/*"]
        remotePath: "/"
    verify:
      enabled: true
      fileTemplate: "deploy-verify-{timestamp}.html"
      urlTemplate: "https://{domain}/{file}"
